language: node_js

node_js:
- 4.5.0

git:
  submodules: false

branches:
  only:
  - master
  
before_install:
- npm install hexo -g
- npm install hexo-cli -g
- npm install grunt-cli -g
- npm install bower -g
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
  
install:
- npm install
- cd themes/tranquilpeak
- npm install
- bower install
- npm run prod
- cd ../..

before_script:
- git config --global user.name 'James McCollum'
- git config --global user.email 'jmccollum@signet-studios.com'

script:
- hexo generate

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Automatic publish with Travis-CI'
- git branch -m gh-pages
- git push -q -u origin gh-pages
