language: node_js

node_js:
- node

branches:
  only:
  - master
  
install:
- npm install

before_script:
- git config user.name 'James McCollum'
- git config user.email 'jmccollum@signet-studios.com'

script:
- hexo generate

after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch gh-pages --single-branch $DEPLOY_REPO . || (git init && git remote add -t gh-pages origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Automatic deploy with Travis-CI'
- git branch -m gh-pages
- git push -q -u origin gh-pages