language: node_js

node_js:
- 4.5.0

git:
  submodules: false

branches:
  only:
  - master
  
before_install:
- npm install hexo-cli -g
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
  
install:
- npm install

before_script:
- git config --global user.name 'James McCollum'
- git config --global user.email 'jmccollum@signet-studios.com'

script:
- hexo generate

after_success:
- hexo deploy